create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float4, delete_flag boolean, id bigint not null, timestamp timestamp(6), currency_name varchar(255), primary key (id));
create table gateway.rate_historical (delete_flag boolean, success boolean, date timestamp(6), id bigint not null, timestamp timestamp(6), base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float4, delete_flag boolean, id bigint not null, timestamp timestamp(6), currency_name varchar(255), primary key (id));
create table gateway.rate_historical (delete_flag boolean, success boolean, date timestamp(6), id bigint not null, timestamp timestamp(6) not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float4, delete_flag boolean, id bigint not null, timestamp timestamp(6), currency_name varchar(255), primary key (id));
create table gateway.rate_historical (delete_flag boolean, success boolean, date timestamp(6), id bigint not null, timestamp timestamp(6) not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float4, delete_flag boolean, id bigint not null, timestamp timestamp(6), currency_name varchar(255), primary key (id));
create table gateway.rate_historical (delete_flag boolean, success boolean, date timestamp(6), id bigint not null, timestamp timestamp(6) not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float4, delete_flag boolean, id bigint not null, timestamp timestamp(6) with time zone, currency_name varchar(255), primary key (id));
create table gateway.rate_historical (delete_flag boolean, success boolean, date timestamp(6), id bigint not null, timestamp timestamp(6) with time zone not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float4, delete_flag boolean, id bigint not null, timestamp timestamp(6) with time zone, currency_name varchar(255), primary key (id));
create table gateway.rate_historical (date date, delete_flag boolean, success boolean, id bigint not null, timestamp timestamp(6) with time zone not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float(53), delete_flag boolean, id bigint not null, timestamp timestamp(6) with time zone, currency_name varchar(255), primary key (id));
create table gateway.rate_historical (date date, delete_flag boolean, success boolean, id bigint not null, timestamp timestamp(6) with time zone not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float(53), delete_flag boolean, id bigint not null, timestamp timestamp(6) with time zone, currency_name varchar(255), primary key (id));
create table gateway.rate_historical (date date, delete_flag boolean, success boolean, id bigint not null, timestamp timestamp(6) with time zone not null unique, base varchar(255), primary key (id));
create sequence gateway.rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float(53), delete_flag boolean, id bigint not null, timestamp timestamp(6) with time zone, currency_name varchar(255), primary key (id));
create table gateway.rate_historical (date date, delete_flag boolean, success boolean, id bigint not null, timestamp timestamp(6) with time zone not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway_egt.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway_egt.rate (currency_value float(53), delete_flag boolean, id bigint not null, timestamp timestamp(6) with time zone, currency_name varchar(255), primary key (id));
create table gateway_egt.rate_historical (date date, delete_flag boolean, success boolean, id bigint not null, timestamp timestamp(6) with time zone not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway_egt.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway_egt.rate (currency_value float(53), delete_flag boolean, id bigint not null, timestamp timestamp(6) with time zone, currency_name varchar(255), primary key (id));
create table gateway_egt.rate_historical (date date, delete_flag boolean, success boolean, id bigint not null, timestamp timestamp(6) with time zone not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
create table gateway.audit_log (end_client_id bigint, id bigint not null, time timestamp(6), request_id varchar(255), service_id varchar(255), primary key (id));
create table gateway.rate (currency_value float(53), delete_flag boolean, id bigint not null, timestamp timestamp(6) with time zone, currency_name varchar(255), primary key (id));
create table gateway.rate_historical (date date, delete_flag boolean, success boolean, id bigint not null, timestamp timestamp(6) with time zone not null unique, base varchar(255), primary key (id));
create sequence rate_sequence start with 1 increment by 1;
